version: 2.1

orbs:

  shellcheck: circleci/shellcheck@1

  build:
    jobs:

      run-build:
        parameters:
          image-tag:
            description: The .NET Core SDK image tag to use.
            type: string
          build-config:
            description: The build configuration, either Debug or Release.
            type: string
          framework:
            description: The .NET Core App framework target.
            type: string
        executor:
          name: dotnet-build-executor
          tag: << parameters.image-tag >>
        steps:
          - checkout
          - run:
              name: Test Coverage
              command: ./coverage.sh << parameters.framework >> << parameters.build-config >>
          - store_artifacts:
              path: ./test/TestResults/coverage.json
              destination: coverage.json
          - store_artifacts:
              path: ./test/TestResults/coverage.opencover.xml
              destination: coverage.opencover.xml
          - store_artifacts:
              path: ./test/TestResults/Report/
              destination: report
          - store_test_results:
              path: ./test/TestResults/output/

    executors:

      dotnet-build-executor:
        parameters:
          tag:
            description: The .NET Core SDK image tag to use.
            type: string
        docker:
          - image: mcr.microsoft.com/dotnet/core/sdk:<<parameters.tag>>

workflows:

  "Build All Frameworks":
    jobs:
      - shellcheck/check:
          name: shellcheck
      - build/run-build:
          name: 2.1.700 Debug Build
          image-tag: "2.1.700"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1.700 Release Build
          image-tag: "2.1.700"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2.300 Debug Build
          image-tag: "2.2.300"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2.300 Release Build
          image-tag: "2.2.300"
          build-config: Release
          framework: netcoreapp2.1


      - build/run-build:
          name: 2.1.604 Debug Build
          image-tag: "2.1.604"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.1.604 Release Build
          image-tag: "2.1.604"
          build-config: Release
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2.204 Debug Build
          image-tag: "2.2.204"
          build-config: Debug
          framework: netcoreapp2.1
      - build/run-build:
          name: 2.2.204 Release Build
          image-tag: "2.2.204"
          build-config: Release
          framework: netcoreapp2.1
